= Guess Number

image::https://github.com/kbyyd24/guess-number-practice/workflows/day-1/badge.svg[link="https://github.com/kbyyd24/guess-number-practice/actions"]

== 练习描述

实现猜数字的游戏。游戏有四个格子，每个格子有一个0到9的数字，任意两个格子的数字都不一样。你有6次猜测的机会，如果猜对则获胜，否则失败。每次猜测时需依序输入4个数字，程序会根据猜测的情况给出xAxB的反馈，A前面的数字代表位置和数字都对的个数，B前面的数字代表数字对但是位置不对的个数。
例如：答案是1 2 3 4， 那么对于不同的输入，有如下的输出

|===
| Input | Output | Instruction

| 1 5 6 7
| 1A0B
| 1 correct

| 2 4 7 8
| 0A2B
| 2 and 4 wrong position

| 0 3 2 4
| 1A2B
| 4 correct，2 and 3 wrong position

| 5 6 7 8
| 0A0B
| all wrong

| 4 3 2 1
| 0A4B
| 4 numbers position wrong

| 1 2 3 4
| 4A0B
| win, all correct

| 1 1 2 3
| Wrong Input, input again
| Wrong Input, input again

| 1 2
| Wrong Input, input again
| Wrong Input, input again
|===

答案在游戏开始时随机生成。输入只有6次机会，在每次猜测时，程序应给出当前猜测的结果，以及之前所有猜测的数字和结果以供玩家参考。

【理解】
一、关于Controller部分：
逻辑抽出来
重构前：
NumberGuesser:
在{..}里面做:1、转成String对象流 2、做逻辑判断，一个一个比较字符是否正确以及是否在正确的位置上.
Map<String,Long> xx = IntStream.range(,).mapToObj(i->{..})
    .filter() .collect(groupingBy(identity(),counting()))

重构后：
走到数字正确后：根据数字是否在正确的位置上分类，并count。把A、B的数目分别赋给FinalResult

Map<Boolean,Long> xx=IntStream.range(,)
    .filter().boxed.collect(partitioningBy(digitIsCorrect(),counting))

重构后，把判断逻辑当作方法抽出去了。

逻辑里面的语法重构
重构前：
分别将String类型的answer和guessed进行charAt，然后用.indexOf() 返回字符在字符串中第一次出现处的索引

重构后：
answer做成List<Character>,通过List.get()的方法来获取其中的字符。避免了一个一个charAt

二、关于Result部分：
重构前：
GameResult=String cuurent+ List<Result> Previous
current result是String:由guess生成
Result=String input(guessedNumber)+String result(current result) 真正的结果由输入+输出生成
最终的结果是进行追加

重构后：
逻辑是一样的，加了一个RuntimeException


总体逻辑架构：
Entity:
OneGuessResult 可以获得(String)input (String)output
GuessResult 可以获得(String)current (List<OneGuessResult>)previous (String) message
CheckResult 可以获得(long)correctCount (long)wrongPositionCount

Answer类： check方法返回CheckResult
ResultFormatter类： format方法会返回固定格式的String，RuntimeException会被其他地方捕捉到"Wrong input.."

NumberGenerator类：generate方法生成满足需求的答案

Controller层：guess方法返回GuessResult，这里会对previous的大小进行判断（设置previous的作用）

TDD:
1、Entity
2、一轮
3、六轮